### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Rudloff** [abozanona/User-Behavior-in-Facebook#4]
Hello,
What is the license of the Android app? I could not find any license file.

**Comment by abozanona** [comment]
It's under MIT License. We'll include the licence file and copyright notice later.

**Comment by IzzySoft** [comment]
How much later? It's still missing.

**Comment by IzzySoft** [comment]
Obviously still later. It's been a year now. Sure you're still on it, @abozanona? Your [request for F-Droid inclusion](https://gitlab.com/fdroid/rfp/issues/542) is still stalled waiting for this, so maybe we shall rather close it as we cannot process it?

@MeqdadDarweesh did your 👎 apply to the license, or to the "later"?

**Comment by MeqdadDev** [comment]
@IzzySoft 
It's done..
good luck.

**Comment by IzzySoft** [comment]
Thanks! As @abozanona meanwhile closed the RFP: Are you going to reopen it? We don't want to override the author's decision.
